#####################
#  Services         #
#####################
services:
  app:
    restart: always
    container_name: log
    volumes:
      - ${PWD}:/app
    #Where Dockerfile exists
    build:
      context: ../.
      dockerfile: ./docker/dev.Dockerfile
    image: markmain/node:19.4.0
    ports:
      - 3000:3000
    networks:
      - express-mongo
  mongo:
    restart: always
    container_name: mongodb
    image: mongo:6.0.3
    volumes:
      - ../data/db:/data/db
      - ../data/configdb:/data/configdb
    networks:
      - express-mongo
    ports:
      - "27017:27017"

#####################
#  Networks         #
#####################
networks:
  express-mongo:

